import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ThemeRegistry from '@/theme/ThemeRegistry';
import Navbar from '../components/Navbar';
import Navhead from '../components/Navhead';
import Box from '@mui/material/Box';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout(props) {
    const { children } = props;

    return (
        <html lang='en'>
            <body>
                {/* <Navbar sx={{ backgroundColor: '#000' }} /> */}
                <Navbar />
                <Box sx={{ display: 'flex', justifyContent: 'center' }}>
                    <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
                </Box>
            </body>
        </html>
    );
}
